---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/alandiaz/.config/auth0
    containerPath: "/auth0"
    readOnly: true
  - hostPath: ./
    containerPath: "/auth"
    readOnly: true  
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    containerLogMaxSize: 100Mi
    containerLogMaxFiles: 10
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # LOGGING LEVEL
        v: "6"
        # STRUCTURED AUTHENTICATION FLAG
        authentication-config: /auth/kubeapi-authn-config.yaml
      
      extraVolumes:
      - name: "auth0"
        hostPath: "/auth0"
        mountPath: "/auth0"
        readOnly: true
      - name: "auth"
        hostPath: "/auth"
        mountPath: "/auth"
        readOnly: true

