apiVersion: v1
kind: Pod
metadata:
  labels:
    run: p1
  name: p1
spec:
  initContainers:
  - name: myapp-initializer
    image: example/initializer:v1.0.0
  containers:
  - image: nginx
    name: p1
