# The configuration file uses the kubeconfig file format. Within the file "users" refers to the API Server webhook and "clusters" refers to the remote service.
apiVersion: v1
kind: Config
clusters:
- name: opa-authz-webhook
  cluster:
    # For the purpose of the demo we use a self-signed certificate.
    # This should obviously be changed for production purposes.
    insecure-skip-tls-verify: true
    # Use static IP configured for service as the kubernetes DNS service (CoreDNS)
    # can't be used by the API server (as that would be a circular dependency).
    server: http://localhost:30001/v0/data/system/main
users:
- name: api-server  
  user:
    # Authentication method to use for accessing OPA itself
    # See https://www.openpolicyagent.org/docs/latest/security/#authentication-and-authorization
    token: test-token
current-context: webhook
contexts:
- context:
    cluster: opa-authz-webhook
    user: api-server
  name: webhook
