---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: "image-pull-policy"
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["pods"]
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  matchConditions:
   - name: has-labels
     expression: "has(object.metadata.labels)"
   - name: platform-pods-only
     expression: "has(object.metadata.labels.platform)"
  mutations:
    - patchType: "ApplyConfiguration"
      applyConfiguration:
        expression: >
          Object{
            spec: Object.spec{
              containers: object.spec.containers.map(c, Object.spec.containers{
                  name: c.name,
                  imagePullPolicy: "Never"
                })
            }
          }