---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
  extraMounts:
  - hostPath: ${pwd}/audit
    containerPath: "/etc/kubernetes/audit"
    readOnly: true
  - hostPath: ${pwd}/authn-config
    containerPath: "/auth"
    readOnly: true
  - hostPath: ${pwd}/authz-config
    containerPath: /etc/kubernetes/api-server
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    containerLogMaxSize: 100Mi
    containerLogMaxFiles: 10
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # LOGGING LEVEL
        v: "8"
        # AUDIT LOGGING
        audit-policy-file: "/etc/kubernetes/audit/audit-policy.yaml"
        audit-log-path: /var/log/kubernetes/audit.log
        audit-log-maxage: "30" # Number of days to retain audit logs
        audit-log-maxbackup: "3" # Number of audit log files to retain
        audit-log-maxsize: "100" # Maximum size in MB of audit log files before rotation
        # STRUCTURED AUTHENTICATION FLAG
        authentication-config: /auth/apiserver-structured-authn-config.yaml
        # STRUCTURED AUTHORIZATION FLAGS
        authorization-config: /etc/kubernetes/api-server/structured-authz-config.yaml

      extraVolumes:
      - name: "audit"
        hostPath: "/etc/kubernetes/audit"
        mountPath: "/etc/kubernetes/audit"
        readOnly: true
      - name: "authn"
        hostPath: "/auth"
        mountPath: "/auth"
        readOnly: true
      - name: api-server
        hostPath: /etc/kubernetes/api-server
        mountPath: /etc/kubernetes/api-server