---
apiVersion: v1
kind: Pod 
metadata:
  name: multi-container
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: busybox-container
      image: busybox:latest
      command: ["sh", "-c", "while true; do sleep 3600; done"]