---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
    - name: busybox-container
      image: busybox:latest
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000