---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-resource-pod
spec:
  containers:
  - name: c1
    image: nginx:alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: c2
    image: alpine
    command: ["sh", "-c", "sleep infinity"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
  - name: c3
    image: alpine
    command: ["sh", "-c", "sleep infinity"]