---
apiVersion: v1
kind: Pod
metadata:
  name: platform-pod
  labels:
    platform: "true"
spec:
  containers: # containers should get imagePullPolicy: Always by mutatingadmissionpolicy 
    - name: c1
      image: nginx:alpine
    - name: c2
      image: alpine
      command: ["sh", "-c", "sleep infinity"]