---
apiVersion: v1
kind: Pod
metadata:
  name: simple-resource-pod
spec:
  containers:
  - name: simple-resource-container
    image: nginx:alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"