---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
  extraMounts:
  - hostPath: ${pwd}/authn-config
    containerPath: "/auth"
    readOnly: true
  - hostPath: ${pwd}/authz-webhook
    containerPath: /etc/kubernetes/api-server
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    containerLogMaxSize: 100Mi
    containerLogMaxFiles: 10
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # LOGGING LEVEL
        v: "6"
        # STRUCTURED AUTHENTICATION FLAG
        authentication-config: /auth/apiserver-structured-authn-config.yaml
        # AUTHORIZATION FLAGS
        authorization-mode: Node,RBAC
        #authorization-webhook-version: v1
        #authorization-webhook-config-file: /etc/kubernetes/api-server/authz-webhook-kubeconfig.yaml
      
      extraVolumes:
      - name: "authn"
        hostPath: "/auth"
        mountPath: "/auth"
        readOnly: true
      - name: api-server
        hostPath: /etc/kubernetes/api-server
        mountPath: /etc/kubernetes/api-server