---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  MutatingAdmissionPolicy: true # Required for k8s 1.32
runtimeConfig:
  "api/alpha": true # Required for k8s 1.32
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
  extraMounts:
  - hostPath: ${pwd}/audit
    containerPath: "/etc/kubernetes/audit"
    readOnly: true
  - hostPath: ./audit-logs/
    containerPath: /var/log/kubernetes/
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    containerLogMaxSize: 100Mi
    containerLogMaxFiles: 10
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # LOGGING LEVEL
        v: "8"
        # AUDIT LOGGING
        audit-policy-file: "/etc/kubernetes/audit/audit-policy.yaml"
        audit-log-path: /var/log/kubernetes/audit.log
        audit-log-maxage: "30" # Number of days to retain audit logs
        audit-log-maxbackup: "3" # Number of audit log files to retain
        audit-log-maxsize: "100" # Maximum size in MB of audit log files before rotation
        
      extraVolumes:
      - name: "audit"
        hostPath: "/etc/kubernetes/audit"
        mountPath: "/etc/kubernetes/audit"
        readOnly: true
      - name: audit-log
        hostPath: "/var/log/kubernetes/"
        mountPath: "/var/log/kubernetes/"